---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  require_chef_omnibus: false

platforms:
- name: ubuntu-12.04
  driver:
    box: ubuntu-12.04
    box_url: http://mirrors.ooyala.com/vagrant/ubuntu1204.box

suites:
- name: default
  data_bags_path: 'test/integration/data_bags'
  run_list:
    - recipe[rancid-git]
  attributes:
    region: "sv2"
    rancid:
      configs:
        groups: ["sjc1"]
